### ISSUE TITLE
interop.intents.raises schema doesn't match FDC3 spec

### ISSUE THREAD

**Issue by kriswest** [finos-labs/FDC3-App-Directory#30]
Originally raised on the FDC3 repository as: https://github.com/finos/FDC3/issues/1085

The app directory is serving records where the `interop.intents.raises` don't match the specification in the Standard. They are incorrectly using the schema for `interop.intents.listensFor`. See:
https://github.com/finos-labs/FDC3-App-Directory/blob/main/_apps/adaptabledemo.json#L64-L78

and compare to the spec: https://fdc3.finos.org/schemas/2.1/app-directory.html#tag/Application/paths/~1v2~1apps~1%7BappId%7D/get
![image](https://github.com/finos-labs/FDC3-App-Directory/assets/1701764/9832e9d6-aca2-4aa9-baf6-a7a4b7da6b31)

**Comment by kriswest** [comment]
Kalina found another similar issue:

> I found another issue with Fino's directory. appChannels prop in adaptabledemo should be an array of objects and not an object.

**Comment by robmoffat** [comment]
@andreifloricel can you take a look?

**Comment by andreifloricel** [comment]
@robmoffat sure, I'll take a look in the coming days.
